// Auto-generate basic Playwright E2E smoke tests by analyzing Next.js app routes
// Scans src/app/**/page.tsx and emits tests/generated-routes.spec.ts
// Safe to run repeatedly; it overwrites the generated file each time.

const fs = require("fs");
const path = require("path");

function findRoutes(appDir) {
  const routes = [];

  // Root route
  const rootPage = path.join(appDir, "page.tsx");
  if (fs.existsSync(rootPage)) {
    routes.push("/");
  }

  const entries = fs.readdirSync(appDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const name = entry.name;
    // Exclude API and special Next.js folders
    if (name === "api" || name.startsWith("(") || name.startsWith("_"))
      continue;

    const pageFile = path.join(appDir, name, "page.tsx");
    if (fs.existsSync(pageFile)) {
      routes.push(`/${name}`);
    }
  }

  // Deterministic order
  routes.sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
  return routes;
}

function toSafeName(route) {
  return route.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "root";
}

function generateSpecContent(routes) {
  const header = `// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.
// Generated by scripts/generate-e2e.js based on src/app/**/page.tsx
import { test, expect } from "@playwright/test";

test.describe("Generated E2E - Route smoke tests", () => {
`;

  const tests = routes
    .map((route) => {
      const name = toSafeName(route);
      return `  test("loads ${route}", async ({ page }) => {
    await page.goto("${route}");
    await page.waitForLoadState("networkidle");
    await expect(page.locator("body")).toBeVisible();
    await page.screenshot({ path: "generated-${name}.png", fullPage: true });
  });`;
    })
    .join("\n\n");

  const footer = `\n});\n`;
  return `${header}${tests}${footer}`;
}

(function main() {
  const appDir = path.resolve(process.cwd(), "src", "app");
  const testsDir = path.resolve(process.cwd(), "tests");
  const outFile = path.join(testsDir, "generated-routes.spec.ts");

  if (!fs.existsSync(appDir)) {
    console.warn("[generate-e2e] src/app not found. Skipping generation.");
    process.exit(0);
  }
  if (!fs.existsSync(testsDir)) {
    fs.mkdirSync(testsDir, { recursive: true });
  }

  const routes = findRoutes(appDir);
  const content = generateSpecContent(routes);
  fs.writeFileSync(outFile, content, "utf8");
  console.log(
    `[generate-e2e] Wrote ${outFile} with ${routes.length} route tests.`,
  );
})();
