// Auto-generate basic Playwright E2E smoke tests by analyzing Next.js app routes
// Scans src/app/**/page.tsx and emits tests/generated-routes.spec.ts
// Safe to run repeatedly; it overwrites the generated file each time.

const fs = require("fs");
const path = require("path");

function loadConfig(rootDir) {
  const cfgPath = path.join(rootDir, "e2e.config.json");
  if (!fs.existsSync(cfgPath)) return null;
  try {
    const raw = fs.readFileSync(cfgPath, "utf8");
    const json = JSON.parse(raw);
    return json;
  } catch (e) {
    console.warn("[generate-e2e] Failed to parse e2e.config.json:", e?.message);
    return null;
  }
}

function findRoutes(appDir, cfg) {
  const routes = [];

  // Root route
  const rootPage = path.join(appDir, "page.tsx");
  if (fs.existsSync(rootPage)) {
    routes.push("/");
  }

  const entries = fs.readdirSync(appDir, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const name = entry.name;
    // Exclude API and special Next.js folders
    if (name === "api" || name.startsWith("(") || name.startsWith("_"))
      continue;

    const pageFile = path.join(appDir, name, "page.tsx");
    if (fs.existsSync(pageFile)) {
      routes.push(`/${name}`);
    }
  }

  // Apply excludes from config (exact or prefix match when pattern ends with '/*')
  const excludes = (cfg?.exclude || []).filter(Boolean);
  const filtered = routes.filter((r) => {
    for (const pat of excludes) {
      if (typeof pat !== "string") continue;
      if (pat.endsWith("/*")) {
        const base = pat.slice(0, -2);
        if (r === base || r.startsWith(base + "/")) return false;
      } else if (r === pat) {
        return false;
      }
    }
    return true;
  });

  // Deterministic order
  filtered.sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
  return filtered;
}

function toSafeName(route) {
  return route.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "root";
}

function compileAction(action) {
  if (!action || typeof action !== "object") return "";
  const s = (v) => String(v).replace(/`/g, "\\`");
  switch (action.type) {
    case "fill":
      return `      await page.locator(${JSON.stringify(
        action.selector,
      )}).first().fill(${JSON.stringify(action.value ?? "")});`;
    case "click":
      return `      await page.locator(${JSON.stringify(
        action.selector,
      )}).first().click();`;
    case "expectVisible":
      return `      await expect(page.locator(${JSON.stringify(
        action.selector,
      )})).toBeVisible();`;
    case "waitForSelector":
      return `      await page.waitForSelector(${JSON.stringify(
        action.selector,
      )});`;
    case "waitForTimeout":
      return `      await page.waitForTimeout(${Number(action.ms ?? 300)});`;
    default:
      return "";
  }
}

function generateSpecContent(routes, cfg) {
  const header =
    `// THIS FILE IS AUTO-GENERATED. DO NOT EDIT.\n` +
    `// Generated by scripts/generate-e2e.cjs based on src/app/**/page.tsx\n` +
    (cfg ? `// Using e2e.config.json to augment actions\n` : "") +
    `import { test, expect } from "@playwright/test";\n\n` +
    `test.describe("Generated E2E - Route smoke tests", () => {\n` +
    `  test.setTimeout(30_000);\n`;

  const tests = routes
    .map((route) => {
      const name = toSafeName(route);
      const routeCfg = cfg?.routes?.find?.((r) => r?.path === route);
      const injected = Array.isArray(routeCfg?.actions)
        ? routeCfg.actions.map(compileAction).filter(Boolean).join("\n")
        : "";
      return (
        `  test("loads ${route}", async ({ page }) => {\n` +
        `    await page.goto("${route}");\n` +
        `    await page.waitForLoadState("networkidle");\n` +
        `    await expect(page.locator("body")).toBeVisible();\n` +
        `    // Try basic interactions if elements exist (best-effort, non-failing)\n` +
        `    try {\n` +
        `      const firstInput = page.locator('input[type="text"], input:not([type]), textarea').first();\n` +
        `      if (await firstInput.count()) {\n` +
        `        await firstInput.fill('test');\n` +
        `        await page.waitForTimeout(200);\n` +
        `      }\n` +
        `      const firstButton = page.locator('button, [role="button"], input[type="submit"]').first();\n` +
        `      if (await firstButton.count()) {\n` +
        `        await firstButton.click({ trial: true }).catch(() => {});\n` +
        `      }\n` +
        `      const firstForm = page.locator('form').first();\n` +
        `      if (await firstForm.count()) {\n` +
        `        await firstForm.evaluate(el => el.dispatchEvent(new Event('submit', { bubbles: true }))).catch(() => {});\n` +
        `      }\n` +
        `    } catch { /* ignore */ }\n` +
        (injected
          ? `    // Injected actions from e2e.config.json (route: ${route})\n` +
            injected +
            "\n"
          : "") +
        `    await page.screenshot({ path: "generated-${name}.png", fullPage: true });\n` +
        `  });`
      );
    })
    .join("\n\n");

  const footer = `\n});\n`;
  return `${header}${tests}${footer}`;
}

(function main() {
  const appDir = path.resolve(process.cwd(), "src", "app");
  const testsDir = path.resolve(process.cwd(), "tests");
  const outFile = path.join(testsDir, "generated-routes.spec.ts");
  const rootDir = process.cwd();
  const cfg = loadConfig(rootDir);

  if (!fs.existsSync(appDir)) {
    console.warn("[generate-e2e] src/app not found. Skipping generation.");
    process.exit(0);
  }
  if (!fs.existsSync(testsDir)) {
    fs.mkdirSync(testsDir, { recursive: true });
  }

  const routes = findRoutes(appDir, cfg);
  const content = generateSpecContent(routes, cfg);
  fs.writeFileSync(outFile, content, "utf8");
  console.log(
    `[generate-e2e] Wrote ${outFile} with ${routes.length} route tests.`,
  );
})();
